// Compiles the Tollpad contracts with solc-js, along with Uniswap's own pool
// manager: the tests run against the real thing rather than a stand-in, so it
// has to come out of the same compile.
//
// It also checks the one thing about this build that is not like the others —
// the hook's address has to carry its permission flags in its low 14 bits, so
// the deploy scripts need the hook's creation code to mine a salt against. That
// is written out here rather than reconstructed later, where it could drift.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const solc = require("solc");

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");
const mockDir = join(here, "test", "mocks");
const outDir = join(here, "out");
// The site imports these, so they are generated rather than copied: the
// frontend cannot drift from the contracts it is calling.
const abiDir = resolve(here, "..", "site", "src", "lib", "abi");

function collectSources(dir, prefix = "") {
  const sources = {};
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) Object.assign(sources, collectSources(join(dir, entry.name), rel));
    else if (entry.name.endsWith(".sol")) sources[rel] = { content: readFileSync(join(dir, entry.name), "utf8") };
  }
  return sources;
}

// v4-core and v4-periphery are Foundry projects, and their sources import their
// own dependencies through remappings that npm knows nothing about.
const REMAPPINGS = [
  ["solmate/", "@uniswap/v4-core/lib/solmate/"],
  ["permit2/", "@uniswap/v4-periphery/lib/permit2/"],
  ["openzeppelin-contracts/", "@uniswap/v4-core/lib/openzeppelin-contracts/"],
];

/** Every source solc pulled in through the callback, keyed by the path it asked for. */
const resolved = {};

function findImports(path) {
  const asked = path;
  try {
    for (const [from, to] of REMAPPINGS) {
      if (path.startsWith(from)) path = to + path.slice(from.length);
    }
    const contents = path.startsWith("@")
      ? readFileSync(require.resolve(path, { paths: [here] }), "utf8")
      : readFileSync(join(srcDir, path), "utf8");

    resolved[asked] = { content: contents };
    return { contents };
  } catch (error) {
    return { error: `not found: ${asked} (${error.message})` };
  }
}

const sources = collectSources(srcDir);
// Keyed under mocks/ so their `../` imports resolve to the same source entries
// the contracts themselves use.
if (existsSync(mockDir)) Object.assign(sources, collectSources(mockDir, "mocks"));

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "cancun",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImports }));

const diagnostics = output.errors ?? [];
for (const d of diagnostics) console.error(d.formattedMessage.trimEnd());
if (diagnostics.some((d) => d.severity === "error")) {
  console.error("\ncompile failed");
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
mkdirSync(abiDir, { recursive: true });

const DEPLOYED = {
  "TollpadFactory.sol": "TollpadFactory",
  "TollHook.sol": "TollHook",
  "TollLocker.sol": "TollLocker",
  "TollToken.sol": "TollToken",
};

const TEST_ONLY = {
  "mocks/TestVenue.sol": ["TestPoolManager", "TestSwapRouter"],
};

const limit = 24576; // EIP-170 deployed-bytecode ceiling

for (const [file, name] of Object.entries(DEPLOYED)) {
  const artifact = output.contracts[file][name];
  writeFileSync(join(outDir, `${name}.json`), JSON.stringify(artifact, null, 2));

  const size = artifact.evm.deployedBytecode.object.length / 2;
  const status = size > limit ? "OVER EIP-170 LIMIT" : "ok";
  console.log(`${name.padEnd(16)} ${String(size).padStart(6)} bytes deployed  ${status}`);
  if (size > limit) process.exitCode = 1;

  const constName = `${name.replace(/^./, (c) => c.toLowerCase())}Abi`;
  writeFileSync(
    join(abiDir, `${name.replace(/^./, (c) => c.toLowerCase())}.ts`),
    `// Generated by contracts/compile.mjs — do not edit by hand.\n` +
      `export const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
}

for (const [file, names] of Object.entries(TEST_ONLY)) {
  for (const name of names) {
    writeFileSync(join(outDir, `${name}.json`), JSON.stringify(output.contracts[file][name], null, 2));
  }
}

// The same compilation, standing on its own: every import inlined, no callback
// needed. This is what an explorer is handed at verification time, and it is
// worth proving rather than assuming — an input that compiles to different
// bytecode is rejected on submission, which is a slow way to find out.
const standalone = { ...input, sources: { ...resolved, ...input.sources } };
const check = JSON.parse(solc.compile(JSON.stringify(standalone)));

const checkErrors = (check.errors ?? []).filter((d) => d.severity === "error");
if (checkErrors.length > 0) {
  for (const d of checkErrors) console.error(d.formattedMessage.trimEnd());
  console.error("\nthe standalone verification input does not compile");
  process.exit(1);
}

for (const [file, name] of Object.entries(DEPLOYED)) {
  const mine = output.contracts[file][name].evm.deployedBytecode.object;
  const theirs = check.contracts?.[file]?.[name]?.evm?.deployedBytecode?.object;
  if (mine !== theirs) {
    console.error(`${name}: the verification input compiles to different bytecode — do not submit it`);
    process.exit(1);
  }
}

writeFileSync(join(outDir, "solc-input.json"), JSON.stringify(standalone, null, 2));

console.log(`\nartifacts written to ${outDir}`);
console.log(`ABIs written to ${abiDir}`);
console.log(`verification input written, ${Object.keys(standalone.sources).length} sources, bytecode matches`);
